import { COLUMN_NAMES } from './columns';

const { FIRST, SECOND, THIRD, FORTH, FIFTH } = COLUMN_NAMES;
export const firstCards = [
	{
		id: '0',
		firstName: 'Maedeh',
		lastName: 'Farahani',
		tel: '0638692275',
		adresseMail: 'Maed.farahani@gmail.com',
		photo: 'cersei-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/maedeh-farahani-25a5a1172/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIRST,
	},
	{
		id: '1',
		firstName: 'Jon',
		lastName: 'Snow',
		tel: '0638692324',
		adresseMail: 'Sabarad@yahoo.com',
		photo: 'jon-snow.jpg',
		linkedin: 'https://www.linkedin.com/in/john-snow-44b71446/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIRST,
	},
	{
		id: '2',
		firstName: 'Tywin',
		lastName: 'Lannister',
		tel: '0638699876',
		adresseMail: 'Twin123@yahoo.com ',
		photo: 'tywin-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tywin-lannister-5b8215239/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIRST,
	},
	{
		id: '3',
		firstName: 'Tyrion',
		lastName: 'Lannister',
		tel: '0638696543',
		adresseMail: 'tyrionLani@yahoo.fr',
		photo: 'tyrion-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tyrion-lannister-4118bb234/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIRST,
	},
	{
		id: '4',
		firstName: 'Daenerys',
		lastName: 'Targaryen',
		tel: '0638692275',
		adresseMail: 'DaennerysTarag@yahoo.com',
		photo: 'daenerys-targaryen.jpg',
		linkedin: 'https://www.linkedin.com/in/daenerys-targaryen-b62a60123/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIRST,
	},
];

export const secondCards = [
	{
		id: '0',
		firstName: 'Maedeh',
		lastName: 'Farahani',
		tel: '0638692275',
		adresseMail: 'Maed.farahani@gmail.com',
		photo: 'cersei-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/maedeh-farahani-25a5a1172/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: SECOND,
	},
	{
		id: '1',
		firstName: 'Jon',
		lastName: 'Snow',
		tel: '0638692324',
		adresseMail: 'Sabarad@yahoo.com',
		photo: 'jon-snow.jpg',
		linkedin: 'https://www.linkedin.com/in/john-snow-44b71446/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: SECOND,
	},
	{
		id: '2',
		firstName: 'Tywin',
		lastName: 'Lannister',
		tel: '0638699876',
		adresseMail: 'Twin123@yahoo.com ',
		photo: 'tywin-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tywin-lannister-5b8215239/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: SECOND,
	},
	{
		id: '3',
		firstName: 'Tyrion',
		lastName: 'Lannister',
		tel: '0638696543',
		adresseMail: 'tyrionLani@yahoo.fr',
		photo: 'tyrion-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tyrion-lannister-4118bb234/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: SECOND,
	},
	{
		id: '4',
		firstName: 'Daenerys',
		lastName: 'Targaryen',
		tel: '0638692275',
		adresseMail: 'DaennerysTarag@yahoo.com',
		photo: 'daenerys-targaryen.jpg',
		linkedin: 'https://www.linkedin.com/in/daenerys-targaryen-b62a60123/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: SECOND,
	},
];

export const thirdCards = [
	{
		id: '0',
		firstName: 'Maedeh',
		lastName: 'Farahani',
		tel: '0638692275',
		adresseMail: 'Maed.farahani@gmail.com',
		photo: 'cersei-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/maedeh-farahani-25a5a1172/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: THIRD,
	},
	{
		id: '1',
		firstName: 'Jon',
		lastName: 'Snow',
		tel: '0638692324',
		adresseMail: 'Sabarad@yahoo.com',
		photo: 'jon-snow.jpg',
		linkedin: 'https://www.linkedin.com/in/john-snow-44b71446/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: THIRD,
	},
	{
		id: '2',
		firstName: 'Tywin',
		lastName: 'Lannister',
		tel: '0638699876',
		adresseMail: 'Twin123@yahoo.com ',
		photo: 'tywin-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tywin-lannister-5b8215239/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: THIRD,
	},
	{
		id: '3',
		firstName: 'Tyrion',
		lastName: 'Lannister',
		tel: '0638696543',
		adresseMail: 'tyrionLani@yahoo.fr',
		photo: 'tyrion-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tyrion-lannister-4118bb234/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: THIRD,
	},
	{
		id: '4',
		firstName: 'Daenerys',
		lastName: 'Targaryen',
		tel: '0638692275',
		adresseMail: 'DaennerysTarag@yahoo.com',
		photo: 'daenerys-targaryen.jpg',
		linkedin: 'https://www.linkedin.com/in/daenerys-targaryen-b62a60123/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: THIRD,
	},
];

export const forthCards = [
	{
		id: '0',
		firstName: 'Maedeh',
		lastName: 'Farahani',
		tel: '0638692275',
		adresseMail: 'Maed.farahani@gmail.com',
		photo: 'cersei-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/maedeh-farahani-25a5a1172/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FORTH,
	},
	{
		id: '1',
		firstName: 'Jon',
		lastName: 'Snow',
		tel: '0638692324',
		adresseMail: 'Sabarad@yahoo.com',
		photo: 'jon-snow.jpg',
		linkedin: 'https://www.linkedin.com/in/john-snow-44b71446/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FORTH,
	},
	{
		id: '2',
		firstName: 'Tywin',
		lastName: 'Lannister',
		tel: '0638699876',
		adresseMail: 'Twin123@yahoo.com ',
		photo: 'tywin-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tywin-lannister-5b8215239/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FORTH,
	},
	{
		id: '3',
		firstName: 'Tyrion',
		lastName: 'Lannister',
		tel: '0638696543',
		adresseMail: 'tyrionLani@yahoo.fr',
		photo: 'tyrion-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tyrion-lannister-4118bb234/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FORTH,
	},
	{
		id: '4',
		firstName: 'Daenerys',
		lastName: 'Targaryen',
		tel: '0638692275',
		adresseMail: 'DaennerysTarag@yahoo.com',
		photo: 'daenerys-targaryen.jpg',
		linkedin: 'https://www.linkedin.com/in/daenerys-targaryen-b62a60123/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FORTH,
	},
];

export const fifthCards = [
	{
		id: '0',
		firstName: 'Maedeh',
		lastName: 'Farahani',
		tel: '0638692275',
		adresseMail: 'Maed.farahani@gmail.com',
		photo: 'cersei-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/maedeh-farahani-25a5a1172/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIFTH,
	},
	{
		id: '1',
		firstName: 'Jon',
		lastName: 'Snow',
		tel: '0638692324',
		adresseMail: 'Sabarad@yahoo.com',
		photo: 'jon-snow.jpg',
		linkedin: 'https://www.linkedin.com/in/john-snow-44b71446/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIFTH,
	},
	{
		id: '2',
		firstName: 'Tywin',
		lastName: 'Lannister',
		tel: '0638699876',
		adresseMail: 'Twin123@yahoo.com ',
		photo: 'tywin-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tywin-lannister-5b8215239/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIFTH,
	},
	{
		id: '3',
		firstName: 'Tyrion',
		lastName: 'Lannister',
		tel: '0638696543',
		adresseMail: 'tyrionLani@yahoo.fr',
		photo: 'tyrion-lannister.jpg',
		linkedin: 'https://www.linkedin.com/in/tyrion-lannister-4118bb234/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIFTH,
	},
	{
		id: '4',
		firstName: 'Daenerys',
		lastName: 'Targaryen',
		tel: '0638692275',
		adresseMail: 'DaennerysTarag@yahoo.com',
		photo: 'daenerys-targaryen.jpg',
		linkedin: 'https://www.linkedin.com/in/daenerys-targaryen-b62a60123/',
		behance: 'https://www.linkedin.com/in/christopher-debray/',
		github: 'https://github.com/Maedeh-vasheghani',
		column: FIFTH,
	},
];
